controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # Kontrolcü Listesi
    gimbal_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Gimbal Kontrolcüsünün Ayarları
gimbal_controller:
  ros__parameters:
    joints:
      - gimbal_yaw_joint
      - gimbal_pitch_joint